### PR TITLE
Issue-1

### PR DESCRIPTION
**Pull request by voronov007**
Moved getPiece function to the getPiece.js

Solved Issue-#1

### CODE REVIEW

**Comment by SrNightmare09** [comment]
@voronov007 Have you cross-checked that the application works the same as before after your code modification?

**Comment by voronov007** [comment]
@SrNightmare09 yes

**Comment by SrNightmare09** [comment]
@voronov007 It does indeed work! Thank you so much for this contribution. I wonder why it was not working for me when I tried putting the function in a different file.

**Comment by voronov007** [comment]
Because you were needed also to add a path to the script and do it before other scripts:

```
    <script defer src="getPiece.js"></script>
    <script defer src="read.js"></script>
    <script defer src="generateBoard.js"></script>
```

**Comment by SrNightmare09** [comment]
@voronov007 Oh I see! I knew we had to declare them in the html file but I was not aware that the ordered mattered! Thank you for informing me of this!

**Pull request merged**
